---
- name: Create kubernetes script directory
  file: path={{ kube_script_dir }} state=directory

- name: Create system kube-cert groups
  group: name={{ kube_cert_group }} state=present system=yes

- name: Create system kube user
  user:
    name=kube
    comment="Kubernetes user"
    shell=/sbin/nologin
    state=present
    system=yes
    groups={{ kube_cert_group }}

- name: make sure the certificate directory exits
  file:
    path={{ kube_cert_dir }}
    state=directory
    mode=o-rwx
    group={{ kube_cert_group }}

- name: make sure the tokens directory exits
  file:
    path={{ kube_token_dir }}
    state=directory
    mode=o-rwx
    group={{ kube_cert_group }}

- include: gen_certs.yml
  when: inventory_hostname == groups['masters'][0]

- name: Read back the CA certificate
  slurp:
    src: "{{ kube_cert_dir }}/ca.crt"
  register: ca_cert
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Register the CA certificate as a fact so it can be used later
  set_fact:
    kube_ca_cert: "{{ ca_cert.content|b64decode }}"

- name: Place CA certificate and kube_cfg credentials everywhere
  copy: content="{{ kube_ca_cert }}" dest="{{ kube_cert_dir }}/ca.crt"

- name: Read back the server key
  slurp:
    src: "{{ kube_cert_dir }}/server.key"
  register: api_key
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Register the cfg key as a fact so it can be used later
  set_fact:
    kube_server_key: "{{ api_key.content|b64decode }}"

- name: Place CA certificate and server credentials everywhere
  copy: content="{{ kube_server_key }}" dest="{{ kube_cert_dir }}/server.key"

- name: Read back the server cert
  slurp:
    src: "{{ kube_cert_dir }}/server.crt"
  register: api_crt
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Register the server cert as a fact so it can be used later
  set_fact:
    kube_server_crt: "{{ api_crt.content|b64decode }}"

- name: Place CA certificate and server credentials everywhere
  copy: content="{{ kube_server_crt }}" dest="{{ kube_cert_dir }}/server.crt"

- name: Read back the kubecfg key
  slurp:
    src: "{{ kube_cert_dir }}/kubecfg.key"
  register: api_key
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Register the cfg key as a fact so it can be used later
  set_fact:
    kube_api_key: "{{ api_key.content|b64decode }}"

- name: Place CA certificate and kube_cfg credentials everywhere
  copy: content="{{ kube_api_key }}" dest="{{ kube_cert_dir }}/kubecfg.key"

- name: Read back the kubecfg cert
  slurp:
    src: "{{ kube_cert_dir }}/kubecfg.crt"
  register: api_crt
  run_once: true
  delegate_to: "{{ groups['masters'][0] }}"

- name: Register the cfg cert as a fact so it can be used later
  set_fact:
    kube_api_crt: "{{ api_crt.content|b64decode }}"

- name: Place CA certificate and kube_cfg credentials everywhere
  copy: content="{{ kube_api_crt }}" dest="{{ kube_cert_dir }}/kubecfg.crt"
  notify:
    - restart daemons

- name: Verify certificate permissions
  file:
    path={{ item }}
    group={{ kube_cert_group }}
    owner=kube
    mode=0440
  with_items:
    - "{{ kube_cert_dir }}/ca.crt"
    - "{{ kube_cert_dir }}/server.crt"
    - "{{ kube_cert_dir }}/server.key"
    - "{{ kube_cert_dir }}/kubecfg.crt"
    - "{{ kube_cert_dir }}/kubecfg.key"

- include: gen_tokens.yml
  when: inventory_hostname == groups['masters'][0]
